"""CLI: propeller-resolve"""

import json
from pathlib import Path

import click
import yaml

from ..models import Pipeline
from ..pipeline import resolve, pipeline_to_dict


LOCK_HEADER = "# AUTO-GENERATED - DO NOT EDIT\n# This file is generated by `propeller-resolve`. Edit propeller.yaml instead.\n\n"


def _generate_mermaid(pipeline: Pipeline, highlight: list[str] | None = None, action: str | None = None) -> str:
    """Generate a Mermaid flowchart from the resolved pipeline.

    Args:
        pipeline: The resolved pipeline.
        highlight: Optional list of project names to visually highlight
                   (e.g. when using the ONLY filter).
        action: Optional deploy action (plan, apply, destroy, sleep, wake) to
                determine styling.
    """
    highlighted = set(highlight or [])
    is_sleep_wake = action in ("sleep", "wake")

    # Use bottom-to-top for sleep (reverse execution), top-down otherwise
    direction = "BT" if action == "sleep" else "TD"
    lines = [f"graph {direction}"]

    # Define style classes
    if is_sleep_wake:
        if action == "sleep":
            lines.append("  classDef destroy fill:#ef5350,stroke:#c62828,stroke-width:2px,color:#fff")
            lines.append("  classDef command fill:#ab47bc,stroke:#6a1b9a,stroke-width:2px,color:#fff")
        else:  # wake
            lines.append("  classDef destroy fill:#66bb6a,stroke:#2e7d32,stroke-width:2px,color:#fff")
            lines.append("  classDef command fill:#ab47bc,stroke:#6a1b9a,stroke-width:2px,color:#fff")
        lines.append("  classDef skip fill:none,stroke:#9e9e9e,stroke-dasharray:5 5,color:#9e9e9e")
    elif highlighted:
        if action == "destroy":
            lines.append("  classDef highlighted fill:#ef5350,stroke:#c62828,stroke-width:2px,color:#fff")
        else:
            lines.append("  classDef highlighted fill:#f9a825,stroke:#f57f17,stroke-width:2px,color:#000")
        lines.append("  classDef dimmed fill:none,stroke:#9e9e9e,stroke-dasharray:5 5,color:#9e9e9e")

    # Build step lookup for sleep_config
    step_lookup: dict[str, object] = {}
    for stage in pipeline.stages:
        for step in stage.steps:
            step_lookup[step.project] = step

    # Render stages (reversed visually for sleep)
    render_stages = list(reversed(pipeline.stages)) if action == "sleep" else pipeline.stages

    for i, stage in enumerate(render_stages):
        stage_node = f"stage_{stage.name}"
        lines.append(f"  {stage_node}([{stage.name}])")

        # Connect previous stage's steps to this stage node
        if i > 0:
            prev_stage = render_stages[i - 1]
            for step in prev_stage.steps:
                dependents = {
                    s.project for s in prev_stage.steps if step.project in s.depends_on
                }
                if not dependents:
                    lines.append(f"  {step.project} --> {stage_node}")

        # Connect stage node to root steps (no in-stage deps)
        for step in stage.steps:
            if not step.depends_on:
                lines.append(f"  {stage_node} --> {step.project}")

        # In-stage dependency edges
        for step in stage.steps:
            for dep in step.depends_on:
                lines.append(f"  {dep} --> {step.project}")

    # Apply classes
    if is_sleep_wake:
        for project, step in step_lookup.items():
            if not step.sleep:
                lines.append(f"  class {project} skip")
            elif step.sleep_config:
                sleep_action = step.sleep_config.get("action", "skip")
                if sleep_action in ("destroy", "command"):
                    lines.append(f"  class {project} {sleep_action}")
                else:
                    lines.append(f"  class {project} skip")
            else:
                lines.append(f"  class {project} skip")
    elif highlighted:
        all_projects = {step.project for stage in pipeline.stages for step in stage.steps}
        for project in highlighted:
            lines.append(f"  class {project} highlighted")
        for project in all_projects - highlighted:
            lines.append(f"  class {project} dimmed")

    return "\n".join(lines) + "\n"


@click.command()
@click.option(
    "--base", required=True, type=click.Path(exists=True), help="Base pipeline.yaml"
)
@click.option(
    "--overrides",
    default=None,
    type=click.Path(exists=True),
    help="Override propeller.overrides.yaml (optional)",
)
@click.option("--output", required=True, type=click.Path(), help="Output lock file")
@click.option(
    "--propeller-dir", default=".propeller", help="Path to propeller framework"
)
@click.option(
    "--version",
    "version",
    default=None,
    help="Framework version to stamp into the lock. Overrides the version from "
    "--overrides; required for pipelines without an overrides file.",
)
@click.option(
    "--graph/--no-graph",
    default=True,
    help="Generate Mermaid graph alongside lock file",
)
@click.option(
    "--highlight",
    default=None,
    help="Comma-separated project names to highlight in the graph (e.g. for ONLY filter)",
)
@click.option(
    "--action",
    "action",
    default=None,
    help="Deploy action (plan, apply, destroy) — affects highlight style in the graph",
)
def main(
    base: str,
    overrides: str | None,
    output: str,
    propeller_dir: str,
    version: str | None,
    graph: bool,
    highlight: str | None,
    action: str | None,
) -> None:
    """Resolve a base pipeline with optional overrides."""
    pipeline = resolve(
        Path(base),
        Path(overrides) if overrides else None,
        propeller_dir,
        version=version,
    )
    out = Path(output)
    data = pipeline_to_dict(pipeline)

    out.write_text(LOCK_HEADER + yaml.dump(data, default_flow_style=False, sort_keys=False))
    click.echo(f"Resolved pipeline written to {out}")

    json_path = out.with_suffix(".json")
    json_path.write_text(json.dumps(data, indent=2) + "\n")
    click.echo(f"Pipeline JSON written to {json_path}")

    if graph:
        graph_path = out.with_suffix(".md")
        highlight_list = [h.strip() for h in highlight.split(",")] if highlight else None
        mermaid = _generate_mermaid(pipeline, highlight=highlight_list, action=action)
        graph_path.write_text(f"# Pipeline Graph\n\n```mermaid\n{mermaid}```\n")
        click.echo(f"Pipeline graph written to {graph_path}")
