"""Human-readable report of how each project was assembled.

Committed as a golden file, so a change in layering shows up as a diff rather than
an opaque assertion failure. Paths are made relative so the report is identical on
any machine.
"""

from __future__ import annotations

from pathlib import Path


def _relative(path: str, roots: dict[str, Path]) -> str:
    p = Path(path).resolve()
    for label, root in roots.items():
        try:
            return f"<{label}>/{p.relative_to(root.resolve())}"
        except ValueError:
            continue
    return str(p)


def _files(root: Path) -> set[str]:
    return {
        str(f.relative_to(root)) for f in root.rglob("*") if f.is_file()
    }


def build(
    manifest: dict,
    bundle_root: Path,
    roots: dict[str, Path],
    cases: dict[str, str],
    specs: dict[str, str] | None = None,
) -> str:
    """Render the report for an extracted bundle.

    `cases` maps project name to what it exercises, and must cover every project.
    `specs` maps project name to the `source:` value as written in the pipeline,
    which the resolved paths in the manifest no longer show.
    """
    specs = specs or {}
    missing = [p["name"] for p in manifest["projects"] if p["name"] not in cases]
    if missing:
        raise KeyError(
            "no case recorded in cases.yaml for: " + ", ".join(sorted(missing))
        )

    lines = [
        "# Bundle assembly report",
        "",
        "Generated by `tests/report.py`. Regenerate with `pytest --update-golden`.",
        "",
        "`from` names the directory each file came from. Layers are applied in the",
        "order listed, so a later one overwrites a file of the same name from an",
        "earlier one. `mirrored` means the file was already in the bundle from the",
        "copy of the whole framework tree, before any project was placed.",
        "",
        "## Reference forms",
        "",
        "How each `source:` in the pipeline was written, and what it resolved to.",
        "",
    ]

    seen: dict[str, str] = {}
    for project in manifest["projects"]:
        spec = specs.get(project["name"])
        if spec and spec not in seen:
            resolved = next(
                (
                    _relative(layer["from"], roots)
                    for layer in project["layers"]
                    if layer["kind"] == "source"
                ),
                _relative(project["resolved_source"], roots),
            )
            seen[spec] = resolved
    width = max((len(s) for s in seen), default=0)
    for spec, resolved in seen.items():
        lines.append(f"    {spec:<{width}}  ->  {resolved}")
    lines.append("")

    for project in manifest["projects"]:
        name = project["name"]
        layers = project["layers"]
        dest = bundle_root / project["bundle_path"]

        lines.append(f"## {name}")
        lines.append("")
        lines.append(cases[name].strip())
        lines.append("")
        if name in specs:
            lines.append(f"    written  source: {specs[name]}")
        lines.append(f"    path     {project['bundle_path']}")
        chain = " -> ".join(
            f"{layer['kind']}({_relative(layer['from'], roots)})" for layer in layers
        )
        lines.append(f"    layers   {chain}")
        lines.append("")

        if not dest.is_dir():
            lines.append("    (no files)")
            lines.append("")
            continue

        # Last layer containing a path is the one that supplied it. Layers of the
        # same kind are numbered, since with two overlays the kind alone does not
        # say which one won.
        counts: dict[str, int] = {}
        for layer in layers:
            counts[layer["kind"]] = counts.get(layer["kind"], 0) + 1
        seen_of_kind: dict[str, int] = {}
        supplied: dict[str, str] = {}
        for layer in layers:
            kind = layer["kind"]
            seen_of_kind[kind] = seen_of_kind.get(kind, 0) + 1
            label = kind if counts[kind] == 1 else f"{kind} {seen_of_kind[kind]}"
            layer_root = Path(layer["from"])
            if not layer_root.is_dir():
                continue
            for rel in _files(layer_root):
                supplied[rel] = label

        width = max(len(f) for f in _files(dest))
        for rel in sorted(_files(dest)):
            lines.append(f"    {rel:<{width}}  from {supplied.get(rel, 'mirrored')}")
        lines.append("")

    return "\n".join(lines)
